modLoader="javafml"
loaderVersion="[36,)"

license="MIT"
issueTrackerURL="https://github.com/Hellish-Mods/Modern-Custom-Discs/issues"

[[mods]]
modId="moderncustomdiscs"
version="${file.jarVersion}"

displayName="Modern Custom Discs"
displayURL="https://www.curseforge.com/minecraft/mc-mods/modern-custom-discs"
logoFile="pack.png"

authors="Hellish Mods & Modern Modpacks"
credits="""
G_cat (Coding)
"""

description="A simple mod that allows you to add custom discs"

[[dependencies.moderncustomdiscs]]
    modId="forge"
    mandatory=true

    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.moderncustomdiscs]]
    modId="minecraft"
    mandatory=true

    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"